# Generated by Django 4.2 on 2023-04-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='update',
            new_name='updated',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated',
        ),
    ]
